# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.16.1/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.16.1/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/hymanzhou/CLionProjects/my-leetcode-cpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/hymanzhou/CLionProjects/my-leetcode-cpp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.16.1/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.16.1/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/hymanzhou/CLionProjects/my-leetcode-cpp/CMakeFiles /Users/hymanzhou/CLionProjects/my-leetcode-cpp/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/hymanzhou/CLionProjects/my-leetcode-cpp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named 1226-The-Dining-Philosophers

# Build rule for target.
1226-The-Dining-Philosophers: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 1226-The-Dining-Philosophers
.PHONY : 1226-The-Dining-Philosophers

# fast build rule for target.
1226-The-Dining-Philosophers/fast:
	$(MAKE) -f CMakeFiles/1226-The-Dining-Philosophers.dir/build.make CMakeFiles/1226-The-Dining-Philosophers.dir/build
.PHONY : 1226-The-Dining-Philosophers/fast

#=============================================================================
# Target rules for targets named 1195-Fizz-Buzz-Multithreaded

# Build rule for target.
1195-Fizz-Buzz-Multithreaded: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 1195-Fizz-Buzz-Multithreaded
.PHONY : 1195-Fizz-Buzz-Multithreaded

# fast build rule for target.
1195-Fizz-Buzz-Multithreaded/fast:
	$(MAKE) -f CMakeFiles/1195-Fizz-Buzz-Multithreaded.dir/build.make CMakeFiles/1195-Fizz-Buzz-Multithreaded.dir/build
.PHONY : 1195-Fizz-Buzz-Multithreaded/fast

#=============================================================================
# Target rules for targets named 1114-Print-in-Order

# Build rule for target.
1114-Print-in-Order: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 1114-Print-in-Order
.PHONY : 1114-Print-in-Order

# fast build rule for target.
1114-Print-in-Order/fast:
	$(MAKE) -f CMakeFiles/1114-Print-in-Order.dir/build.make CMakeFiles/1114-Print-in-Order.dir/build
.PHONY : 1114-Print-in-Order/fast

#=============================================================================
# Target rules for targets named 1117-Building-H2O

# Build rule for target.
1117-Building-H2O: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 1117-Building-H2O
.PHONY : 1117-Building-H2O

# fast build rule for target.
1117-Building-H2O/fast:
	$(MAKE) -f CMakeFiles/1117-Building-H2O.dir/build.make CMakeFiles/1117-Building-H2O.dir/build
.PHONY : 1117-Building-H2O/fast

#=============================================================================
# Target rules for targets named 1116-Print-Zero-Even-Odd

# Build rule for target.
1116-Print-Zero-Even-Odd: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 1116-Print-Zero-Even-Odd
.PHONY : 1116-Print-Zero-Even-Odd

# fast build rule for target.
1116-Print-Zero-Even-Odd/fast:
	$(MAKE) -f CMakeFiles/1116-Print-Zero-Even-Odd.dir/build.make CMakeFiles/1116-Print-Zero-Even-Odd.dir/build
.PHONY : 1116-Print-Zero-Even-Odd/fast

#=============================================================================
# Target rules for targets named 1115-Print-FooBar-Alternately

# Build rule for target.
1115-Print-FooBar-Alternately: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 1115-Print-FooBar-Alternately
.PHONY : 1115-Print-FooBar-Alternately

# fast build rule for target.
1115-Print-FooBar-Alternately/fast:
	$(MAKE) -f CMakeFiles/1115-Print-FooBar-Alternately.dir/build.make CMakeFiles/1115-Print-FooBar-Alternately.dir/build
.PHONY : 1115-Print-FooBar-Alternately/fast

concurrency/1114-Print-in-Order.o: concurrency/1114-Print-in-Order.cpp.o

.PHONY : concurrency/1114-Print-in-Order.o

# target to build an object file
concurrency/1114-Print-in-Order.cpp.o:
	$(MAKE) -f CMakeFiles/1114-Print-in-Order.dir/build.make CMakeFiles/1114-Print-in-Order.dir/concurrency/1114-Print-in-Order.cpp.o
.PHONY : concurrency/1114-Print-in-Order.cpp.o

concurrency/1114-Print-in-Order.i: concurrency/1114-Print-in-Order.cpp.i

.PHONY : concurrency/1114-Print-in-Order.i

# target to preprocess a source file
concurrency/1114-Print-in-Order.cpp.i:
	$(MAKE) -f CMakeFiles/1114-Print-in-Order.dir/build.make CMakeFiles/1114-Print-in-Order.dir/concurrency/1114-Print-in-Order.cpp.i
.PHONY : concurrency/1114-Print-in-Order.cpp.i

concurrency/1114-Print-in-Order.s: concurrency/1114-Print-in-Order.cpp.s

.PHONY : concurrency/1114-Print-in-Order.s

# target to generate assembly for a file
concurrency/1114-Print-in-Order.cpp.s:
	$(MAKE) -f CMakeFiles/1114-Print-in-Order.dir/build.make CMakeFiles/1114-Print-in-Order.dir/concurrency/1114-Print-in-Order.cpp.s
.PHONY : concurrency/1114-Print-in-Order.cpp.s

concurrency/1115-Print-FooBar-Alternately.o: concurrency/1115-Print-FooBar-Alternately.cpp.o

.PHONY : concurrency/1115-Print-FooBar-Alternately.o

# target to build an object file
concurrency/1115-Print-FooBar-Alternately.cpp.o:
	$(MAKE) -f CMakeFiles/1115-Print-FooBar-Alternately.dir/build.make CMakeFiles/1115-Print-FooBar-Alternately.dir/concurrency/1115-Print-FooBar-Alternately.cpp.o
.PHONY : concurrency/1115-Print-FooBar-Alternately.cpp.o

concurrency/1115-Print-FooBar-Alternately.i: concurrency/1115-Print-FooBar-Alternately.cpp.i

.PHONY : concurrency/1115-Print-FooBar-Alternately.i

# target to preprocess a source file
concurrency/1115-Print-FooBar-Alternately.cpp.i:
	$(MAKE) -f CMakeFiles/1115-Print-FooBar-Alternately.dir/build.make CMakeFiles/1115-Print-FooBar-Alternately.dir/concurrency/1115-Print-FooBar-Alternately.cpp.i
.PHONY : concurrency/1115-Print-FooBar-Alternately.cpp.i

concurrency/1115-Print-FooBar-Alternately.s: concurrency/1115-Print-FooBar-Alternately.cpp.s

.PHONY : concurrency/1115-Print-FooBar-Alternately.s

# target to generate assembly for a file
concurrency/1115-Print-FooBar-Alternately.cpp.s:
	$(MAKE) -f CMakeFiles/1115-Print-FooBar-Alternately.dir/build.make CMakeFiles/1115-Print-FooBar-Alternately.dir/concurrency/1115-Print-FooBar-Alternately.cpp.s
.PHONY : concurrency/1115-Print-FooBar-Alternately.cpp.s

concurrency/1116-Print-Zero-Even-Odd.o: concurrency/1116-Print-Zero-Even-Odd.cpp.o

.PHONY : concurrency/1116-Print-Zero-Even-Odd.o

# target to build an object file
concurrency/1116-Print-Zero-Even-Odd.cpp.o:
	$(MAKE) -f CMakeFiles/1116-Print-Zero-Even-Odd.dir/build.make CMakeFiles/1116-Print-Zero-Even-Odd.dir/concurrency/1116-Print-Zero-Even-Odd.cpp.o
.PHONY : concurrency/1116-Print-Zero-Even-Odd.cpp.o

concurrency/1116-Print-Zero-Even-Odd.i: concurrency/1116-Print-Zero-Even-Odd.cpp.i

.PHONY : concurrency/1116-Print-Zero-Even-Odd.i

# target to preprocess a source file
concurrency/1116-Print-Zero-Even-Odd.cpp.i:
	$(MAKE) -f CMakeFiles/1116-Print-Zero-Even-Odd.dir/build.make CMakeFiles/1116-Print-Zero-Even-Odd.dir/concurrency/1116-Print-Zero-Even-Odd.cpp.i
.PHONY : concurrency/1116-Print-Zero-Even-Odd.cpp.i

concurrency/1116-Print-Zero-Even-Odd.s: concurrency/1116-Print-Zero-Even-Odd.cpp.s

.PHONY : concurrency/1116-Print-Zero-Even-Odd.s

# target to generate assembly for a file
concurrency/1116-Print-Zero-Even-Odd.cpp.s:
	$(MAKE) -f CMakeFiles/1116-Print-Zero-Even-Odd.dir/build.make CMakeFiles/1116-Print-Zero-Even-Odd.dir/concurrency/1116-Print-Zero-Even-Odd.cpp.s
.PHONY : concurrency/1116-Print-Zero-Even-Odd.cpp.s

concurrency/1117-Building-H2O.o: concurrency/1117-Building-H2O.cpp.o

.PHONY : concurrency/1117-Building-H2O.o

# target to build an object file
concurrency/1117-Building-H2O.cpp.o:
	$(MAKE) -f CMakeFiles/1117-Building-H2O.dir/build.make CMakeFiles/1117-Building-H2O.dir/concurrency/1117-Building-H2O.cpp.o
.PHONY : concurrency/1117-Building-H2O.cpp.o

concurrency/1117-Building-H2O.i: concurrency/1117-Building-H2O.cpp.i

.PHONY : concurrency/1117-Building-H2O.i

# target to preprocess a source file
concurrency/1117-Building-H2O.cpp.i:
	$(MAKE) -f CMakeFiles/1117-Building-H2O.dir/build.make CMakeFiles/1117-Building-H2O.dir/concurrency/1117-Building-H2O.cpp.i
.PHONY : concurrency/1117-Building-H2O.cpp.i

concurrency/1117-Building-H2O.s: concurrency/1117-Building-H2O.cpp.s

.PHONY : concurrency/1117-Building-H2O.s

# target to generate assembly for a file
concurrency/1117-Building-H2O.cpp.s:
	$(MAKE) -f CMakeFiles/1117-Building-H2O.dir/build.make CMakeFiles/1117-Building-H2O.dir/concurrency/1117-Building-H2O.cpp.s
.PHONY : concurrency/1117-Building-H2O.cpp.s

concurrency/1195-Fizz-Buzz-Multithreaded.o: concurrency/1195-Fizz-Buzz-Multithreaded.cpp.o

.PHONY : concurrency/1195-Fizz-Buzz-Multithreaded.o

# target to build an object file
concurrency/1195-Fizz-Buzz-Multithreaded.cpp.o:
	$(MAKE) -f CMakeFiles/1195-Fizz-Buzz-Multithreaded.dir/build.make CMakeFiles/1195-Fizz-Buzz-Multithreaded.dir/concurrency/1195-Fizz-Buzz-Multithreaded.cpp.o
.PHONY : concurrency/1195-Fizz-Buzz-Multithreaded.cpp.o

concurrency/1195-Fizz-Buzz-Multithreaded.i: concurrency/1195-Fizz-Buzz-Multithreaded.cpp.i

.PHONY : concurrency/1195-Fizz-Buzz-Multithreaded.i

# target to preprocess a source file
concurrency/1195-Fizz-Buzz-Multithreaded.cpp.i:
	$(MAKE) -f CMakeFiles/1195-Fizz-Buzz-Multithreaded.dir/build.make CMakeFiles/1195-Fizz-Buzz-Multithreaded.dir/concurrency/1195-Fizz-Buzz-Multithreaded.cpp.i
.PHONY : concurrency/1195-Fizz-Buzz-Multithreaded.cpp.i

concurrency/1195-Fizz-Buzz-Multithreaded.s: concurrency/1195-Fizz-Buzz-Multithreaded.cpp.s

.PHONY : concurrency/1195-Fizz-Buzz-Multithreaded.s

# target to generate assembly for a file
concurrency/1195-Fizz-Buzz-Multithreaded.cpp.s:
	$(MAKE) -f CMakeFiles/1195-Fizz-Buzz-Multithreaded.dir/build.make CMakeFiles/1195-Fizz-Buzz-Multithreaded.dir/concurrency/1195-Fizz-Buzz-Multithreaded.cpp.s
.PHONY : concurrency/1195-Fizz-Buzz-Multithreaded.cpp.s

concurrency/1226-The-Dining-Philosophers.o: concurrency/1226-The-Dining-Philosophers.cpp.o

.PHONY : concurrency/1226-The-Dining-Philosophers.o

# target to build an object file
concurrency/1226-The-Dining-Philosophers.cpp.o:
	$(MAKE) -f CMakeFiles/1226-The-Dining-Philosophers.dir/build.make CMakeFiles/1226-The-Dining-Philosophers.dir/concurrency/1226-The-Dining-Philosophers.cpp.o
.PHONY : concurrency/1226-The-Dining-Philosophers.cpp.o

concurrency/1226-The-Dining-Philosophers.i: concurrency/1226-The-Dining-Philosophers.cpp.i

.PHONY : concurrency/1226-The-Dining-Philosophers.i

# target to preprocess a source file
concurrency/1226-The-Dining-Philosophers.cpp.i:
	$(MAKE) -f CMakeFiles/1226-The-Dining-Philosophers.dir/build.make CMakeFiles/1226-The-Dining-Philosophers.dir/concurrency/1226-The-Dining-Philosophers.cpp.i
.PHONY : concurrency/1226-The-Dining-Philosophers.cpp.i

concurrency/1226-The-Dining-Philosophers.s: concurrency/1226-The-Dining-Philosophers.cpp.s

.PHONY : concurrency/1226-The-Dining-Philosophers.s

# target to generate assembly for a file
concurrency/1226-The-Dining-Philosophers.cpp.s:
	$(MAKE) -f CMakeFiles/1226-The-Dining-Philosophers.dir/build.make CMakeFiles/1226-The-Dining-Philosophers.dir/concurrency/1226-The-Dining-Philosophers.cpp.s
.PHONY : concurrency/1226-The-Dining-Philosophers.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... 1226-The-Dining-Philosophers"
	@echo "... rebuild_cache"
	@echo "... 1195-Fizz-Buzz-Multithreaded"
	@echo "... 1114-Print-in-Order"
	@echo "... 1117-Building-H2O"
	@echo "... 1116-Print-Zero-Even-Odd"
	@echo "... 1115-Print-FooBar-Alternately"
	@echo "... concurrency/1114-Print-in-Order.o"
	@echo "... concurrency/1114-Print-in-Order.i"
	@echo "... concurrency/1114-Print-in-Order.s"
	@echo "... concurrency/1115-Print-FooBar-Alternately.o"
	@echo "... concurrency/1115-Print-FooBar-Alternately.i"
	@echo "... concurrency/1115-Print-FooBar-Alternately.s"
	@echo "... concurrency/1116-Print-Zero-Even-Odd.o"
	@echo "... concurrency/1116-Print-Zero-Even-Odd.i"
	@echo "... concurrency/1116-Print-Zero-Even-Odd.s"
	@echo "... concurrency/1117-Building-H2O.o"
	@echo "... concurrency/1117-Building-H2O.i"
	@echo "... concurrency/1117-Building-H2O.s"
	@echo "... concurrency/1195-Fizz-Buzz-Multithreaded.o"
	@echo "... concurrency/1195-Fizz-Buzz-Multithreaded.i"
	@echo "... concurrency/1195-Fizz-Buzz-Multithreaded.s"
	@echo "... concurrency/1226-The-Dining-Philosophers.o"
	@echo "... concurrency/1226-The-Dining-Philosophers.i"
	@echo "... concurrency/1226-The-Dining-Philosophers.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

